### ISSUE TITLE
打包步骤写一下

### ISSUE THREAD

**Issue by PlexPt** [williamfzc/BaseDesktopApp#4]
包括如果有外部静态文件， 依赖库，可执行文件（exe）等的打包。
不同平台自动打包不同依赖

**Comment by williamfzc** [comment]
本质上就是做了命令行调用，调用别的都一样啊。

**Comment by PlexPt** [comment]
怎么打包成exe， dmg， deb

**Comment by PlexPt** [comment]
初学，不知道命令顺序

**Comment by williamfzc** [comment]
参考下 https://github.com/SimulatedGREG/electron-vue

**Comment by PlexPt** [comment]
Error: Command failed: python ./example/example.py python: can't open file './example/example.py': [Errno 2] No such file or directory

打包之后会报错， 依赖没打进去

**Comment by williamfzc** [comment]
这些确实不会自动打包进去，可以用外置脚本or自行手打
